language: objective-c
osx_image: xcode12.2

before_script:
    - travis_wait 30 ./bin/carthage bootstrap --use-xcframeworks --cache-builds

script:
    # Build Travis project and run tests
    - xcodebuild -project ShareClient.xcodeproj -scheme Shared build -destination name="iPhone 8" test 
